replicaCount: 1

image:
  repository: your-dockerhub/sausage-backend-report
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

env:
  PORT: "8081"
  DB: "mongodb://admin:adminpassword@mongodb:27017/sausage_reports?authSource=admin"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

strategy:
  type: Recreate  # Указано в задании: Recreate для backend-report